# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 03:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20151224_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='username',
            field=models.ForeignKey(default='ipartner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
