# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20151224_0404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='productos',
            new_name='products_set',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='products',
        ),
        migrations.AddField(
            model_name='productos',
            name='products_set',
            field=models.ManyToManyField(related_name='products_all', to='personal.Producto'),
        ),
    ]
